package workspacesetup

// The product-authored copy for a new workspace's setup checklist.
//
// It is written here rather than generated by an agent for the same reason
// Enact's opening is: nothing in it depends on workspace state, so paying a
// runtime cold start and two model round trips to render it would only mean
// the member waits — and a failed run would greet them with an error.
//
// The parent body is the one place the product explains itself. Keep it to
// four beats, in this order:
//
//  1. what Enact is, in one sentence,
//  2. what an agent needs before it can work here,
//  3. the four steps, each as a link to its own issue,
//  4. that Enact can do any of it for them.
//
// Step bodies say what the step is FOR before they say how to do it. A member
// who does not know why a runtime exists cannot judge whether to skip it.
var copies = map[string]Copy{
	"en": {
		InboxTitle: "Welcome to Enact — four steps to get working",
		InboxBody: "Enact is a workspace where you and AI agents run real work through issues. " +
			"Agents here are teammates: they own issues, comment, and change status.\n\n" +
			"Before one can work for you, this workspace needs a computer to run on, something to work on, " +
			"and a sentence about what this project is. Open the setup issue for the four steps.",
		ParentTitle: "Set up %s",
		ParentBody: `Enact is a workspace where you and AI agents run real work through issues. An agent here is a teammate rather than a chat window: it is assigned an issue, works on it, comments, and moves it to done.

That is also why setup is not cosmetic. An agent runs on a real computer, reads real files, and does better work when it knows what this project is.

## What to do

Four issues are filed under this one. They unblock each other in order, and none of them takes long.

1. **Connect a computer.** Agents run on a machine you control, under your own accounts and credentials. Nothing runs until one is connected.
2. **Connect your code.** Point the workspace at a repository or a local directory. An agent reads it only when a task calls for it.
3. **Tell Enact about this project.** One or two sentences, your stack, and the kind of work you bring here. Every run starts with this, and it is what capability is recommended against.
4. **Review recommended capability.** The Marketplace holds skills, agent templates and Agent Families published in this deployment. Once step 3 is answered, the ones that fit this project are ranked for you.

## You do not have to do it alone

Enact is this workspace's Chief of Staff. Ask her in chat and she will walk you through any of these, or do them with you.

Close this issue when the four steps are done. They close themselves as each one becomes true.`,
		StepTitles: map[Step]string{
			StepRuntime:    "Connect a computer for agents to run on",
			StepRepository: "Connect the code or files this project is about",
			StepProfile:    "Tell Enact what this project is",
			StepCapability: "Review the capability recommended for this project",
		},
		StepBodies: map[Step]string{
			StepRuntime: `An agent needs somewhere to run. Enact does not run your agents in our cloud by default: they run on a machine you control, under your own agent CLI and your own accounts, so your code and credentials stay where they already are.

Open **Runtimes** in the sidebar and follow the install instructions for your machine. A laptop is fine to start.

This closes itself once a runtime is connected.`,
			StepRepository: `Point this workspace at what the work is about — a Git repository, or a directory on a connected machine.

A resource is a pointer, not a copy. An agent checks a repository out only when a task calls for it, and nothing is uploaded to Enact.

Open **Settings → Resources** to add one.

This closes itself once the workspace has a resource.`,
			StepProfile: `Say what this project is: one or two sentences, the stack you work in, and the kind of work you bring here.

Two things read it. Every agent run starts with it, so a run no longer has to infer your conventions from the files. And the Marketplace ranks capability against it, so what gets recommended is about your project rather than about what is popular.

Fill it in under **Settings → Workspace**, or ask Enact in chat — she will ask a few questions and write it for you.

This closes itself once the profile is filled in.`,
			StepCapability: `The Marketplace is a directory of capability published in this deployment: skills, agent templates, Agent Families, and MCP servers. Installing one puts a copy in this workspace that you then edit like anything you wrote yourself.

Once this workspace has a profile, the Marketplace ranks the directory against it and shows what fits at the top, with the reason it matched.

Open **Marketplace** in the sidebar. Ask Enact for a read on what to install and what to change after installing.

This closes itself once you install something, or dismiss the recommendations you do not want.`,
		},
	},

	"zh": {
		InboxTitle: "欢迎使用 Enact —— 四步开始工作",
		InboxBody: "Enact 是一个人和 AI 智能体通过任务一起把事情做完的工作区。这里的智能体是队友：它们可以被指派任务、评论、推进状态。\n\n" +
			"在智能体开始替你干活之前，这个工作区需要一台运行它们的电脑、一份要处理的东西，以及一句话说明这个项目是什么。打开配置任务，里面是四个步骤。",
		ParentTitle: "配置 %s",
		ParentBody: `Enact 是一个人和 AI 智能体通过任务一起把事情做完的工作区。这里的智能体是队友，不是一个聊天窗口：它被指派一个任务，去做，留下评论，然后把任务推进到完成。

所以配置不是走过场。智能体跑在一台真实的电脑上，读真实的文件；它知道这个项目是什么的时候，活会干得更好。

## 要做什么

这个任务下面有四个子任务。它们按顺序互相解锁，每一个都不费时间。

1. **连接一台电脑。** 智能体跑在你自己控制的机器上，用你自己的账号和凭据。没有连接之前，什么都跑不起来。
2. **接入你的代码。** 把工作区指向一个代码仓库或者一个本地目录。只有任务需要时，智能体才会去读。
3. **告诉 Enact 这个项目是什么。** 一两句话、技术栈、你通常拿到这里做的事。每一次运行都从这些信息开始，推荐也是照着它来的。
4. **看看推荐的能力。** Marketplace 里是这个部署下发布的 Skill、智能体模板和智能体家族。第 3 步填完之后，适合这个项目的会被排到前面。

## 不用一个人弄

Enact 是这个工作区的 Chief of Staff。在聊天里问她，她可以带你走完任何一步，或者直接和你一起做。

四步做完之后关掉这个任务。每一步一旦成立，子任务会自己关闭。`,
		StepTitles: map[Step]string{
			StepRuntime:    "连接一台运行智能体的电脑",
			StepRepository: "接入这个项目的代码或文件",
			StepProfile:    "告诉 Enact 这个项目是什么",
			StepCapability: "看看为这个项目推荐的能力",
		},
		StepBodies: map[Step]string{
			StepRuntime: `智能体需要一个运行的地方。Enact 默认不在我们的云上跑你的智能体：它们跑在你自己控制的机器上，用你自己的 agent CLI 和你自己的账号，所以代码和凭据仍然待在它们本来就在的地方。

打开侧边栏的 **运行时**，按你机器的安装说明走一遍。先用一台笔记本就够了。

连上运行时之后，这个子任务会自己关闭。`,
			StepRepository: `把这个工作区指向要处理的东西——一个 Git 仓库，或者某台已连接机器上的一个目录。

资源是一个指针，不是一份拷贝。只有任务需要时智能体才会去检出仓库，不会有东西被上传到 Enact。

打开 **设置 → 资源** 添加一个。

工作区有了资源之后，这个子任务会自己关闭。`,
			StepProfile: `说清楚这个项目是什么：一两句话、你用的技术栈、你通常拿到这里做的事。

有两处会读它。每一次智能体运行都从它开始，运行时不用再从文件里猜你的约定。Marketplace 也照着它给能力排序，所以推荐出来的东西是关于你的项目的，而不是关于什么最流行。

在 **设置 → 工作区** 里填，或者在聊天里找 Enact——她会问几个问题然后替你写好。

填完之后，这个子任务会自己关闭。`,
			StepCapability: `Marketplace 是这个部署下发布的能力目录：Skill、智能体模板、智能体家族和 MCP 服务器。安装一个，是把一份拷贝放进这个工作区，之后你可以像改自己写的东西一样改它。

工作区有了项目画像之后，Marketplace 会照着它给整个目录排序，把匹配的放在最前面，并说明为什么匹配。

打开侧边栏的 **Marketplace**。也可以问 Enact：装哪个、装完要改什么，她会给一份判断。

装了东西、或者把不想要的推荐忽略掉之后，这个子任务会自己关闭。`,
		},
	},

	"ja": {
		InboxTitle: "Enact へようこそ — 4 つのステップで始められます",
		InboxBody: "Enact は、人と AI エージェントがタスクを通じて実際の仕事を進めるワークスペースです。ここでのエージェントは同僚です。タスクを担当し、コメントし、ステータスを動かします。\n\n" +
			"エージェントが働き始める前に、このワークスペースには動かすためのコンピュータ、対象となるもの、そしてこのプロジェクトが何かを一言で説明したものが必要です。セットアップのタスクを開くと 4 つのステップがあります。",
		ParentTitle: "%s のセットアップ",
		ParentBody: `Enact は、人と AI エージェントがタスクを通じて実際の仕事を進めるワークスペースです。ここでのエージェントはチャット窓ではなく同僚です。タスクを割り当てられ、作業し、コメントし、完了まで動かします。

だからセットアップは形式ではありません。エージェントは実在のコンピュータで動き、実在のファイルを読み、このプロジェクトが何かを知っているほど良い仕事をします。

## やること

このタスクの下に 4 つのサブタスクがあります。順に前提を解いていきますが、どれも時間はかかりません。

1. **コンピュータを接続する。** エージェントはあなたが管理するマシン上で、あなた自身のアカウントと認証情報で動きます。接続するまで何も動きません。
2. **コードを接続する。** ワークスペースをリポジトリかローカルディレクトリに向けます。タスクが必要とするときだけエージェントが読みます。
3. **このプロジェクトが何かを伝える。** 一言か二言、技術スタック、ここで扱う仕事の種類。すべての実行がここから始まり、推奨もこれを基準にします。
4. **推奨された能力を見る。** Marketplace には、このデプロイで公開されたスキル、エージェントテンプレート、Agent Family があります。ステップ 3 を答えると、このプロジェクトに合うものが上位に並びます。

## 一人でやる必要はありません

Enact はこのワークスペースの Chief of Staff です。チャットで頼めば、どのステップも案内し、一緒に進めてくれます。

4 つが終わったらこのタスクを閉じてください。各ステップは条件を満たすと自動的に閉じます。`,
		StepTitles: map[Step]string{
			StepRuntime:    "エージェントを動かすコンピュータを接続する",
			StepRepository: "このプロジェクトのコードやファイルを接続する",
			StepProfile:    "このプロジェクトが何かを Enact に伝える",
			StepCapability: "このプロジェクトに推奨された能力を見る",
		},
		StepBodies: map[Step]string{
			StepRuntime: `エージェントには動く場所が必要です。Enact は既定ではあなたのエージェントを当社のクラウドで動かしません。あなたが管理するマシン上で、あなた自身の agent CLI とアカウントで動くので、コードも認証情報も今ある場所にとどまります。

サイドバーの **ランタイム** を開き、お使いのマシン向けのインストール手順に従ってください。まずはノート PC で十分です。

ランタイムが接続されると、このサブタスクは自動的に閉じます。`,
			StepRepository: `仕事の対象を指定します。Git リポジトリか、接続済みマシン上のディレクトリです。

リソースはポインタであってコピーではありません。タスクが必要とするときだけエージェントがチェックアウトし、Enact には何もアップロードされません。

**設定 → リソース** から追加してください。

リソースが 1 つでもあれば、このサブタスクは自動的に閉じます。`,
			StepProfile: `このプロジェクトが何かを書いてください。一言か二言、使っている技術スタック、ここで扱う仕事の種類です。

読み手は 2 つあります。すべてのエージェント実行がここから始まるので、実行のたびにファイルから慣習を推測せずに済みます。そして Marketplace がこれを基準に能力を並べ替えるので、推奨は流行ではなくあなたのプロジェクトについてのものになります。

**設定 → ワークスペース** で記入するか、チャットで Enact に頼んでください。いくつか質問して代わりに書いてくれます。

記入されると、このサブタスクは自動的に閉じます。`,
			StepCapability: `Marketplace は、このデプロイで公開された能力のディレクトリです。スキル、エージェントテンプレート、Agent Family、MCP サーバー。インストールするとこのワークスペースにコピーが置かれ、自分で書いたものと同じように編集できます。

ワークスペースにプロファイルがあると、Marketplace はそれを基準にディレクトリを並べ替え、合うものを上位に、その理由とともに表示します。

サイドバーの **Marketplace** を開いてください。何を入れて何を変えるべきかは Enact に聞けます。

何かをインストールするか、不要な推奨を却下すると、このサブタスクは自動的に閉じます。`,
		},
	},

	"ko": {
		InboxTitle: "Enact에 오신 걸 환영합니다 — 네 단계로 시작하세요",
		InboxBody: "Enact는 사람과 AI 에이전트가 태스크를 통해 실제 일을 함께 진행하는 워크스페이스입니다. 여기서 에이전트는 동료입니다. 태스크를 맡고, 댓글을 달고, 상태를 옮깁니다.\n\n" +
			"에이전트가 일을 시작하려면 이 워크스페이스에 실행할 컴퓨터, 다룰 대상, 그리고 이 프로젝트가 무엇인지에 대한 한 문장이 필요합니다. 셋업 태스크를 열면 네 단계가 있습니다.",
		ParentTitle: "%s 설정하기",
		ParentBody: `Enact는 사람과 AI 에이전트가 태스크를 통해 실제 일을 함께 진행하는 워크스페이스입니다. 여기서 에이전트는 채팅창이 아니라 동료입니다. 태스크를 배정받고, 작업하고, 댓글을 남기고, 완료까지 옮깁니다.

그래서 설정은 형식이 아닙니다. 에이전트는 실제 컴퓨터에서 돌고 실제 파일을 읽으며, 이 프로젝트가 무엇인지 알수록 더 나은 결과를 냅니다.

## 무엇을 하면 되나요

이 태스크 아래에 네 개의 하위 태스크가 있습니다. 순서대로 서로를 풀어주며, 어느 것도 오래 걸리지 않습니다.

1. **컴퓨터를 연결하세요.** 에이전트는 여러분이 관리하는 machine에서, 여러분의 계정과 자격 증명으로 실행됩니다. 연결 전에는 아무것도 실행되지 않습니다.
2. **코드를 연결하세요.** 워크스페이스를 저장소나 로컬 디렉터리로 지정합니다. 태스크가 필요로 할 때만 에이전트가 읽습니다.
3. **이 프로젝트가 무엇인지 알려주세요.** 한두 문장, 사용하는 스택, 여기서 다루는 일의 종류. 모든 실행이 여기서 시작하고, 추천도 이것을 기준으로 합니다.
4. **추천된 역량을 확인하세요.** Marketplace에는 이 배포에서 공개된 스킬, 에이전트 템플릿, Agent Family가 있습니다. 3단계를 답하면 이 프로젝트에 맞는 것이 위로 올라옵니다.

## 혼자 할 필요는 없습니다

Enact는 이 워크스페이스의 Chief of Staff입니다. 채팅으로 부탁하면 어느 단계든 안내하거나 함께 진행해 줍니다.

네 단계가 끝나면 이 태스크를 닫으세요. 각 단계는 조건이 충족되면 스스로 닫힙니다.`,
		StepTitles: map[Step]string{
			StepRuntime:    "에이전트를 실행할 컴퓨터 연결하기",
			StepRepository: "이 프로젝트의 코드나 파일 연결하기",
			StepProfile:    "이 프로젝트가 무엇인지 Enact에 알려주기",
			StepCapability: "이 프로젝트에 추천된 역량 살펴보기",
		},
		StepBodies: map[Step]string{
			StepRuntime: `에이전트에게는 실행할 곳이 필요합니다. Enact는 기본적으로 여러분의 에이전트를 저희 클라우드에서 실행하지 않습니다. 여러분이 관리하는 machine에서 여러분의 agent CLI와 계정으로 실행되므로, 코드와 자격 증명은 원래 있던 자리에 그대로 있습니다.

사이드바의 **런타임**을 열고 사용 중인 machine에 맞는 설치 안내를 따라가세요. 노트북 한 대로 시작해도 충분합니다.

런타임이 연결되면 이 하위 태스크는 스스로 닫힙니다.`,
			StepRepository: `일의 대상을 지정하세요. Git 저장소이거나, 연결된 machine의 디렉터리입니다.

리소스는 포인터이지 사본이 아닙니다. 태스크가 필요로 할 때만 에이전트가 체크아웃하며, Enact로 업로드되는 것은 없습니다.

**설정 → 리소스**에서 추가하세요.

워크스페이스에 리소스가 생기면 이 하위 태스크는 스스로 닫힙니다.`,
			StepProfile: `이 프로젝트가 무엇인지 적어주세요. 한두 문장, 사용하는 스택, 여기서 다루는 일의 종류입니다.

읽는 곳이 두 군데입니다. 모든 에이전트 실행이 여기서 시작하므로 실행마다 파일에서 관례를 추측하지 않아도 됩니다. 그리고 Marketplace가 이것을 기준으로 역량을 정렬하므로, 추천은 유행이 아니라 여러분의 프로젝트에 대한 것이 됩니다.

**설정 → 워크스페이스**에서 채우거나, 채팅으로 Enact에게 부탁하세요. 몇 가지 물어보고 대신 작성해 줍니다.

채워지면 이 하위 태스크는 스스로 닫힙니다.`,
			StepCapability: `Marketplace는 이 배포에서 공개된 역량의 디렉터리입니다. 스킬, 에이전트 템플릿, Agent Family, MCP 서버. 설치하면 이 워크스페이스에 사본이 놓이고, 직접 작성한 것과 똑같이 편집할 수 있습니다.

워크스페이스에 프로필이 있으면 Marketplace가 그것을 기준으로 디렉터리를 정렬해, 맞는 것을 이유와 함께 위에 보여줍니다.

사이드바의 **Marketplace**를 여세요. 무엇을 설치하고 설치 후 무엇을 바꿔야 하는지는 Enact에게 물어보면 됩니다.

무언가를 설치하거나 원하지 않는 추천을 무시하면 이 하위 태스크는 스스로 닫힙니다.`,
		},
	},
}
