#!/usr/bin/env python3
"""Install the `mmm` entry point at a fixed, machine-independent location.

    install_shim.py [--bin-dir DIR] [--root DIR]

The shim is three lines of shell that carry one fact: where this runtime is
installed. It goes under `$HOME` because that is the only path that is correct
without knowing anything about the machine — `PATH` is inherited from whatever
started the daemon and may not include a user bin directory at all, while `HOME`
is guaranteed to be the real one (`server/internal/daemon/daemon.go` leaves it
alone on purpose).

`$MMM_HOME` still wins at runtime, so a stale shim is recoverable: Enact
injects the runtime path into every agent session, and that overrides the baked
one instead of fighting it.

Idempotent — the file is generated, so it is always rewritten.
"""
from __future__ import annotations

import argparse
import os
import stat
import sys

HERE = os.path.dirname(os.path.realpath(__file__))
DEFAULT_ROOT = os.path.dirname(HERE)
DEFAULT_BIN = os.path.join(os.path.expanduser("~"), ".local", "bin")
MARKER = os.path.join(".claude-plugin", "plugin.json")

TEMPLATE = """#!/bin/sh
# Generated by mmm-runtime/scripts/install_shim.py — do not edit.
# Regenerate with: mmm script install_shim
MMM_SHIM_ROOT='%(root)s'
export MMM_SHIM_ROOT
root="${MMM_HOME:-$MMM_SHIM_ROOT}"
if [ ! -f "$root/scripts/mmm" ]; then
  echo "mmm: runtime 不在 $root 了（这个 shim 是照那个路径生成的）。" >&2
  echo "     重装一次：enact mmm setup   或   MMM_HOME=<runtime 目录> mmm where" >&2
  exit 3
fi
exec "$root/scripts/mmm" "$@"
"""


def write_shim(root, bin_dir):
    target = os.path.join(bin_dir, "mmm")
    os.makedirs(bin_dir, exist_ok=True)
    with open(target, "w", encoding="utf-8") as handle:
        handle.write(TEMPLATE % {"root": root})
    mode = os.stat(target).st_mode
    os.chmod(target, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return target


def main(argv):
    parser = argparse.ArgumentParser(description="安装 mmm 入口")
    parser.add_argument("--bin-dir", default=DEFAULT_BIN)
    parser.add_argument("--root", default=DEFAULT_ROOT)
    args = parser.parse_args(argv)

    root = os.path.realpath(os.path.expanduser(args.root))
    if not os.path.isfile(os.path.join(root, MARKER)):
        sys.stderr.write("install_shim: %s 不是一个 runtime checkout（缺 %s）\n" % (root, MARKER))
        return 2
    if not os.path.isfile(os.path.join(root, "scripts", "mmm")):
        sys.stderr.write("install_shim: %s 里没有 scripts/mmm\n" % root)
        return 2

    bin_dir = os.path.realpath(os.path.expanduser(args.bin_dir))
    try:
        target = write_shim(root, bin_dir)
    except OSError as error:
        sys.stderr.write("install_shim: 写不进 %s：%s\n" % (bin_dir, error))
        return 1

    print("入口已装好：%s" % target)
    print("  指向        %s" % root)
    on_path = bin_dir in [os.path.realpath(os.path.expanduser(p))
                          for p in os.environ.get("PATH", "").split(os.pathsep) if p]
    # Not a failure either way: every skill spells the entry point as
    # `~/.local/bin/mmm` precisely so that PATH does not have to be right.
    print("  在 PATH 上  %s" % ("是" if on_path else "否 —— 技能里用的是全路径，不影响"))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
