// Generated by scripts/generate-brand-mark.mjs from design-system/enact/mark-source.svg.
// Do not edit; change the source and re-run the script.

/** viewBox of the mark's own coordinate space. */
export const ENACT_MARK_VIEWBOX = "0 0 800 800";

/** Every visible part of the mark as one path, filled with a single colour or gradient. */
export const ENACT_MARK_PATH =
  "M 82.6080,565.6090 A 358,358 0 0 1 688.6958,188.2956 L 249.5000,355.1900 L 249.5000,265.1900 L 522.2926,161.5288 A 268,268 0 0 0 167.5256,533.3403 Z M 249.5000,412.1900 L 550.5000,297.8100 L 550.5000,387.8100 L 249.5000,502.1900 Z M 717.3920,234.3910 A 358,358 0 0 1 111.3042,611.7044 L 550.5000,444.8100 L 550.5000,534.8100 L 277.7074,638.4712 A 268,268 0 0 0 632.4744,266.6597 Z";

/** Gradient axis in ENACT_MARK_VIEWBOX units (userSpaceOnUse). */
export const ENACT_MARK_GRADIENT = {
  x1: 400,
  y1: 42,
  x2: 400,
  y2: 758,
} as const;

/**
 * Colour-variant stops at 0 / 0.5 / 1. Web and desktop read these through the
 * `--mark-from` / `--mark-mid` / `--mark-to` tokens in
 * packages/ui/styles/tokens.css; mobile and the static SVGs use the literals.
 */
export const ENACT_MARK_STOPS = {
  from: "#066b38",
  mid: "#61a533",
  to: "#86bc25",
} as const;
