import type { DemoAgent, DemoFamily, DemoSkill, Framework } from "./types";

export const frameworks: {
  name: Framework;
  base: string;
  design: string;
  work: string;
  style: string;
  architecture: string;
}[] = [
  {
    name: "Deep Agents",
    base: "规划、文件系统上下文、子 Agent 与可扩展中间件",
    design: "替换上下文策略，加入项目记忆、权限审批与独立验证",
    work: "适配企业模型 → 设计机制 → 组装中间件 → 验证",
    style: "适合在已有 Harness 基础上逐步定制",
    architecture: "企业模型适配 → Deep Agents 循环 → 企业中间件 → 工具 / 沙箱",
  },
  {
    name: "LangGraph",
    base: "执行图、共享状态、检查点与可恢复执行",
    design: "自主设计节点、上下文组装、记忆门禁与人工中断",
    work: "定义状态 Schema → 编排执行图 → 实现节点 → 检查点验证",
    style: "适合需要显式控制工作流与状态迁移的团队",
    architecture:
      "需求 → Planner → Developer → 审批中断 → Test → Reviewer → 交付；失败回到 Developer",
  },
  {
    name: "Pi",
    base: "精简编码循环、工具与扩展入口",
    design: "通过扩展组织企业上下文、工具边界和评审流程",
    work: "确定扩展接口 → 企业工具封装 → 记忆与协作扩展 → 回归验证",
    style: "适合偏好轻量核心、按需扩展的编码工作方式",
    architecture: "企业扩展 → Pi 编码循环 → 受控工具；外层协调器 → 独立评审",
  },
];

const skillRows: [string, string, string, string, string, number[]][] = [
  [
    "core",
    "维护 Runtime 设计契约与领域索引",
    "每次设计或变更前",
    "企业目标、现有蓝图",
    "领域覆盖表、约束清单",
    [1, 2, 20],
  ],
  [
    "init",
    "建立自建 Runtime 的范围与工作区",
    "新建构建任务",
    "框架选择、目标",
    "Runtime 草稿、构建 Issue",
    [1, 11],
  ],
  [
    "discover",
    "澄清内部模型与研发边界",
    "目标不完整时",
    "用户回答、项目约束",
    "需求简报、验收条件",
    [1, 3, 16],
  ],
  [
    "assemble",
    "整合机制与接口契约",
    "各设计角色交接后",
    "机制卡、依赖关系",
    "架构图、实现计划",
    [4, 13, 14],
  ],
  [
    "simulate",
    "演练设计的关键行为",
    "蓝图进入评审时",
    "场景、状态与工具策略",
    "执行轨迹、风险清单",
    [15, 16, 19],
  ],
  [
    "build",
    "将蓝图映射为工程模块",
    "设计确认后",
    "已确认蓝图、接口契约",
    "工程目录、代码示例",
    [3, 10, 11],
  ],
  [
    "verify",
    "独立检验上下文保真和权限边界",
    "首次构建及返工后",
    "构建快照、验收用例",
    "验证报告、缺陷任务",
    [5, 12, 18],
  ],
  [
    "release",
    "冻结版本与使用说明",
    "验证通过且用户确认后",
    "通过的报告、工程清单",
    "发布清单、版本追溯",
    [18, 20],
  ],
  [
    "evolve",
    "处理记忆候选与版本演进",
    "交付任务或发现新约束时",
    "验证证据、候选经验",
    "采纳决定、变更记录",
    [7, 20],
  ],
  [
    "design-behavior",
    "设计身份、目标与单 Agent 循环",
    "规划工作方式时",
    "任务类型、行为规则",
    "循环与停止条件",
    [1, 2, 4],
  ],
  [
    "design-context",
    "设计上下文来源、预算与压缩",
    "上下文设计或保真缺陷出现时",
    "任务目标、架构约束、日志",
    "保护清单、引用与压缩策略",
    [5, 19],
  ],
  [
    "design-knowledge",
    "设计检索和长期记忆生命周期",
    "确定项目知识范围时",
    "知识来源、共享边界",
    "检索策略、候选—验证—采纳门禁",
    [6, 7],
  ],
  [
    "design-execution",
    "设计工具、环境与授权",
    "明确执行能力时",
    "工具清单、企业权限规则",
    "工具矩阵、隔离与回滚方案",
    [9, 10, 11, 12],
  ],
  [
    "design-collaboration",
    "设计多角色协作与状态恢复",
    "需要开发和评审协作时",
    "角色边界、共享状态",
    "交接契约、重试和检查点",
    [13, 14, 15, 16],
  ],
  [
    "design-quality",
    "设计验收、可观测性和资源预算",
    "制定验收条件时",
    "风险清单、预算目标",
    "用例、追踪字段、预算阈值",
    [17, 18, 19],
  ],
  [
    "orchestrate",
    "派工并管理设计与执行交接",
    "构建 Issue 有新用户决定时",
    "Issue、阶段状态、待决事项",
    "子任务、负责人、交接记录",
    [8, 13, 16],
  ],
  [
    "trace",
    "建立需求到发布的证据链",
    "生成产物与版本时",
    "评论、蓝图、验证和发布事件",
    "双向关联、版本差异",
    [11, 17, 20],
  ],
];
export const skills: DemoSkill[] = skillRows.map(
  ([key, purpose, trigger, input, output, domains]) => ({
    id: `demo-skill-${key}`,
    name: `harness-${key}`,
    purpose,
    trigger,
    input,
    output,
    domains,
  }),
);
const roleRows: [string, string, string[], string, string, string][] = [
  [
    "Orchestrator",
    "管理构建任务与角色交接",
    ["core", "init", "orchestrate", "trace"],
    "用户需求与阶段结果",
    "阶段任务、待决事项、交接记录",
    "仅协调；不代替用户批准、不自行发布",
  ],
  [
    "Lead Architect",
    "整合目标、约束与二十领域架构",
    ["core", "discover", "assemble", "design-behavior"],
    "用户回答与机制设计",
    "需求简报、集成蓝图",
    "设计依赖明确后才交给工程师",
  ],
  [
    "Context & Knowledge Designer",
    "负责上下文、知识与记忆生命周期",
    ["design-context", "design-knowledge", "evolve"],
    "项目目标、上下文来源与隐私边界",
    "保护清单、记忆与检索方案",
    "失败尝试不直接变成长期规则",
  ],
  [
    "Runtime Systems Designer",
    "负责工具、权限、环境与多角色协作",
    ["design-execution", "design-collaboration", "simulate"],
    "授权要求与工作方式",
    "工具策略、交接契约、恢复方案",
    "不能批准自己的敏感工具操作",
  ],
  [
    "Runtime Engineer",
    "将蓝图转为工程结构与实现",
    ["build", "assemble"],
    "确认的蓝图、修复任务",
    "工程预览、修复差异",
    "不能给自己的实现签署独立验证",
  ],
  [
    "Independent Verifier",
    "独立检查行为与质量门禁",
    ["verify", "design-quality", "trace"],
    "工程快照与验收条件",
    "验证报告、缺陷与复验记录",
    "发现阻断缺陷必须停止发布",
  ],
  [
    "Release Maintainer",
    "冻结发布版本并完成使用验收",
    ["release", "evolve", "trace"],
    "通过的复验报告与发布决定",
    "发布清单、绑定说明",
    "只有用户明确确认才发布",
  ],
];
export const agents: DemoAgent[] = roleRows.map(
  ([name, responsibility, keys, input, output, boundary], i) => ({
    id: `demo-agent-${i}`,
    name,
    responsibility,
    skills: keys.map((k) => `demo-skill-${k}`),
    input,
    output,
    boundary,
  }),
);
export const family: DemoFamily = {
  id: "demo-family-builders",
  name: "AnyHarness Runtime Builders",
  agentIds: agents.map((a) => a.id),
};
export const domainRows = [
  [
    "任务目标",
    "理解项目、修改代码、补充测试；达到验收条件后停止",
    "contracts/task",
    "每个交付物可追溯到需求",
  ],
  [
    "身份与规则",
    "企业编码助手遵守项目规范；开发者与评审者分离",
    "policy/identity",
    "角色不能绕过授权",
  ],
  [
    "模型调用",
    "内部模型网关；示例 endpoint 为 internal://model，凭证由企业管理",
    "adapters/model",
    "超时、取消和错误结构统一；调用经企业模型网关",
  ],
  [
    "单 Agent 循环",
    "计划 → 观察 → 行动 → 检查；有上限与明确停止条件",
    "runtime/loop",
    "达到目标或预算耗尽时终止",
  ],
  ["上下文", "", "context/assemble", "压缩前后保护字段逐项一致"],
  [
    "知识获取",
    "按项目检索，引用文件路径与版本；过期证据重新读取",
    "knowledge/retrieve",
    "答案保留引用和来源版本",
  ],
  ["长期记忆", "", "memory/lifecycle", "跨项目访问拒绝；候选有验证证据"],
  [
    "Skills",
    "按任务加载版本化 Skill；最小必要指令进入上下文",
    "skills/registry",
    "触发条件与输入输出契约可检查",
  ],
  ["Tools", "", "tools/policy", "未经授权的执行被阻断"],
  [
    "执行环境",
    "每任务隔离沙箱；网络默认关闭；资源限制由企业配置",
    "execution/sandbox",
    "路径逃逸和未许可网络被拒绝",
  ],
  [
    "工作区与产物",
    "项目内工作目录；补丁、日志和报告保留可追溯引用",
    "workspace/artifacts",
    "写入范围固定，产物有版本",
  ],
  [
    "权限",
    "读取允许；写入受限；测试经用户确认；删除与发布拒绝自动执行",
    "policy/authorize",
    "不能由工具输出自行授予权限",
  ],
  [
    "多 Agent 编排",
    "Developer → Reviewer；Explorer 只读探索；构建 Family 与运行角色分离",
    "orchestration/handoff",
    "交接包含任务、约束、证据和未决项",
  ],
  [
    "会话与状态",
    "任务隔离状态；关键动作前保存检查点；事件幂等",
    "state/checkpoint",
    "重复事件不产生重复操作",
  ],
  [
    "调度与恢复",
    "超时重试有上限；失败恢复到检查点；副作用先检查",
    "scheduler/recover",
    "恢复不重复执行已批准动作",
  ],
  [
    "人机交互",
    "自然语言需求配合明确授权卡；遇到歧义继续澄清",
    "interaction/approval",
    "含糊、否定与条件表达不能批准",
  ],
  [
    "可观测性",
    "记录角色、机制、工具决定、输入输出引用；敏感内容脱敏",
    "telemetry/trace",
    "从产物反查原始需求与决定",
  ],
  [
    "验收",
    "独立验证上下文保真、授权、隔离、恢复和任务质量",
    "verification/suite",
    "阻断失败不允许发布",
  ],
  [
    "成本与性能",
    "上下文示例预算 32k；检索 8k、保护 4k、工作 16k、输出 4k",
    "budget/limits",
    "达到预算停止或压缩；不丢失保护字段",
  ],
  [
    "学习与版本",
    "候选经验经验证与用户采纳；蓝图、工程与 Runtime 版本关联",
    "release/manifest",
    "原始失败报告保留；版本可追溯",
  ],
];
export const taskTitles = [
  "澄清企业目标与约束",
  "设计上下文、知识与记忆",
  "设计工具、权限与工作环境",
  "设计行为循环、协作与恢复",
  "组装架构和实现计划",
  "构建 Runtime 工程",
  "独立验证与修复",
  "发布与使用验收",
];
