"use client";
import { ArrowRight, CheckCircle2, CircleHelp, GitBranch, ListChecks, ShieldCheck } from "lucide-react";
import { recordList, recordValue } from "@enact/core/semantic";
import { useSemanticText } from "./shared";

type JourneyProps = { steps: Record<string, unknown>[]; onEvidence: (id: string) => void };

export function BusinessJourney({ steps, onEvidence }: JourneyProps) {
  const t = useSemanticText();
  const completed = steps.filter(s => s.status === "succeeded");
  const last = (kind: string) => recordValue([...completed].reverse().find(s => s.kind === kind)?.output);
  const plan = last("business_plan"), report = last("business_report"), context = last("ontology_context");
  const planSteps = recordList(plan.steps), findings = recordList(report.findings);
  const policies = completed.filter(s => s.kind === "policy_evaluation");
  const objects: Array<Record<string, unknown> & { kind: string }> = ["entities", "attributes", "relationships", "actions", "policies"].flatMap(kind => recordList(context[kind]).map(item => ({ ...item, kind })));
  const labels = new Map(objects.map(o => [String(o.id), String(o.label || "")]));
  const classifications: Record<string, string> = { fact: t("journeyFact"), inference: t("journeyInference"), recommendation: t("journeyRecommendation"), unknown: t("journeyUnknown") };
  const textList = (value: unknown) => Array.isArray(value) ? value.filter((x): x is string => typeof x === "string") : [];
  if (!planSteps.length && !findings.length && !objects.length && !policies.length) return null;
  return <div className="space-y-5" aria-label={t("journeyTitle")}>
    {!!report.summary && <header className="rounded-xl border border-primary/20 bg-primary/5 p-5"><p className="mb-2 flex items-center gap-2 text-caption font-medium text-primary"><CheckCircle2 className="size-4" />{t("journeyFindings")}</p><p className="text-title font-semibold leading-relaxed">{String(report.summary)}</p></header>}
    {planSteps.length > 0 && <section className="rounded-xl border border-border-soft p-5"><h3 className="flex items-center gap-2 text-body font-semibold"><ListChecks className="size-4 text-primary" />{t("journeyPlan")}</h3><p className="mt-2 text-body text-muted-foreground">{String(plan.summary || "")}</p><ol className="mt-4 grid gap-4 md:grid-cols-2">{planSteps.map((step, i) => <li key={i} className="flex gap-3"><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-primary/10 text-caption font-semibold text-primary">{i + 1}</span><div className="min-w-0"><h4 className="text-body font-medium">{String(step.label || "")}</h4><p className="mt-1 text-caption leading-relaxed text-muted-foreground">{String(step.purpose || "")}</p><p className="mt-2 text-caption text-primary">{textList(step.object_ids).map(id => labels.get(id)).filter(Boolean).join(" · ")}</p></div></li>)}</ol>{textList(plan.questions).length > 0 && <aside className="mt-4 rounded-lg bg-muted p-3"><h4 className="text-caption font-medium">{t("journeyQuestions")}</h4><ul className="mt-2 space-y-1 text-body">{textList(plan.questions).map(q => <li key={q}>{q}</li>)}</ul></aside>}</section>}
    {objects.length > 0 && <section><h3 className="mb-3 flex items-center gap-2 text-body font-semibold"><GitBranch className="size-4 text-primary" />{t("journeyObjects")}</h3><div className="flex flex-wrap gap-2">{objects.filter(o => o.kind !== "attributes").slice(0, 30).map(o => <span className="rounded-full border border-border-soft px-3 py-1 text-caption" key={`${o.kind}:${String(o.id)}`} title={String(o.description || "")}>{String(o.label || "")}</span>)}</div></section>}
    {findings.length > 0 && <section className="grid gap-3 md:grid-cols-2">{findings.map((finding, i) => <article key={i} className="rounded-xl border border-border-soft p-4"><span className="text-caption font-medium text-muted-foreground">{classifications[String(finding.classification)] || t("journeyUnknown")}</span><h3 className="mt-2 text-body font-semibold">{String(finding.label || "")}</h3><p className="mt-2 whitespace-pre-wrap text-body leading-relaxed">{String(finding.detail || "")}</p>{textList(finding.evidence_step_ids).length > 0 && <div className="mt-3 flex flex-wrap gap-3">{textList(finding.evidence_step_ids).map((id, n) => <button key={id} onClick={() => onEvidence(id)} className="flex items-center gap-1 text-caption font-medium text-primary underline-offset-4 hover:underline focus-visible:outline-2 focus-visible:outline-ring">{t("journeyEvidence")} {n + 1}<ArrowRight className="size-3" /></button>)}</div>}</article>)}</section>}
    {policies.length > 0 && <section className="rounded-xl border border-border-soft p-5"><h3 className="mb-3 flex items-center gap-2 text-body font-semibold"><ShieldCheck className="size-4 text-primary" />{t("journeyPolicies")}</h3><div className="space-y-3">{policies.map(step => { const result = recordValue(step.output); return <article key={String(step.id)}><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="text-body font-medium">{String(result.action_label || labels.get(String(result.action_id)) || t("journeyAction"))}</h4><span className="rounded-md bg-muted px-2 py-1 text-caption">{result.decision === "deny" ? t("journeyDenied") : result.decision === "unknown" ? t("journeyUnknown") : t("journeyReviewRequired")}</span></div><p className="mt-1 text-caption text-muted-foreground">{String(result.reason || "")}</p><ul className="mt-2 space-y-1">{recordList(result.policies).map((policy, i) => <li className="text-caption" key={i}>{String(policy.label || labels.get(String(policy.policy_id)) || t("journeyPolicy"))} — {String(policy.reason || policy.description || "")}</li>)}</ul></article>; })}</div><p className="mt-4 text-caption text-muted-foreground">{t("journeyPolicyHelp")}</p></section>}
    {(textList(report.next_steps).length > 0 || textList(report.limitations).length > 0) && <section className="grid gap-4 rounded-xl bg-muted/40 p-5 md:grid-cols-2"><div><h3 className="text-body font-semibold">{t("journeyNext")}</h3><ul className="mt-2 space-y-2 text-body">{textList(report.next_steps).map(item => <li key={item}>{item}</li>)}</ul></div><div><h3 className="flex items-center gap-2 text-body font-semibold"><CircleHelp className="size-4" />{t("journeyQuestions")}</h3><ul className="mt-2 space-y-2 text-body text-muted-foreground">{textList(report.limitations).map(item => <li key={item}>{item}</li>)}</ul></div></section>}
  </div>;
}
