ALTER TABLE semantic_connection ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE semantic_release ADD COLUMN IF NOT EXISTS retired_at TIMESTAMPTZ;
ALTER TABLE semantic_release ADD COLUMN IF NOT EXISTS retired_by UUID;
ALTER TABLE semantic_release ADD COLUMN IF NOT EXISTS retirement_reason TEXT NOT NULL DEFAULT '';
ALTER TABLE semantic_step ADD COLUMN IF NOT EXISTS attempt INTEGER NOT NULL DEFAULT 1;
ALTER TABLE semantic_step ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ NOT NULL DEFAULT now();
